CREATE TABLE EMPLOYEES (
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL
);


INSERT INTO EMPLOYEES (ID, NAME, AGE) VALUES (1, 'John Doe', 23);
INSERT INTO EMPLOYEES (ID, NAME, AGE) VALUES (2, 'Jane Doe', 22);